In [1]:
import numpy as np
import pandas as pd

np.random.seed(123)

n_samples = 1000
class_0_ratio = 0.9
n_class_0 = int(n_samples * class_0_ratio)
n_class_1 = n_samples - n_class_0

In [2]:
n_class_0,n_class_1

(900, 100)

In [11]:
class_0 = pd.DataFrame({
    'feature_1' : np.random.normal(loc=0, scale=1,size=n_class_0),
    'feature_2' : np.random.normal(loc=0,scale=1,size=n_class_0),
    'target':[0]*n_class_0
})

class_1 = pd.DataFrame({
    'feature_1' : np.random.normal(loc=2, scale=1,size=n_class_1),
    'feature_2' : np.random.normal(loc=2,scale=1,size=n_class_1),
    'target':[1]*n_class_1
})

In [12]:
df=pd.concat([class_0,class_1]).reset_index(drop=True)

In [13]:
df

     feature_1  feature_2  target
0    -2.643425  -0.093436       0
1    -0.448991   1.650653       0
2    -0.358907  -0.845004       0
3     0.133194   0.395839       0
4    -0.644242  -1.342092       0
..         ...        ...     ...
995   2.317874   0.566811       1
996   4.203088   1.629890       1
997   2.477481   1.715648       1
998   3.767493   2.373888       1
999  -0.205739   2.263030       1

[1000 rows x 3 columns]

In [14]:
df.tail()

     feature_1  feature_2  target
995   2.317874   0.566811       1
996   4.203088   1.629890       1
997   2.477481   1.715648       1
998   3.767493   2.373888       1
999  -0.205739   2.263030       1

In [15]:
df['target'].value_counts()

target
0    900
1    100
Name: count, dtype: int64

In [24]:
#upsampling
df_minority=df[df['target']==1]
df_majority=df[df['target']==0]

In [28]:
from sklearn.utils import resample
df_minority_upsampled = resample(df_minority,replace=True, #Sample with replacement
                                 n_samples=len(df_majority),
                                 random_state=42
                                )

In [29]:
df_minority_upsampled.shape

(900, 3)

In [30]:
df_minority_upsampled.head()

     feature_1  feature_2  target
951   1.850229   2.098445       1
992   1.642404   1.252027       1
914   2.818151   1.567731       1
971   0.838009   1.108123       1
960   0.696935   1.895430       1

In [31]:
df_upsampled=pd.concat([df_majority,df_minority_upsampled])

In [32]:
df_upsampled['target'].value_counts()

target
0    900
1    900
Name: count, dtype: int64

## Downsampling

In [35]:
import pandas as pd

np.random.seed(123)

n_samples = 1000
class_0_ratio = 0.9
n_class_0=int(n_samples * class_0_ratio)
n_class_1 = n_samples - n_class_0

class_0 = pd.DataFrame({
    'feature_1': np.random.normal(loc=0,scale=1,size = n_class_0),
    'feature_2': np.random.normal(loc=0,scale=1,size = n_class_0),
    'target':[0]*n_class_0
})
#loc=0 → centered around 0 or mean around 0
#scale=1 → standard deviation of 1
class_1 = pd.DataFrame({
    'feature_1':np.random.normal(loc=2,scale=1,size=n_class_1),
    'feature_2':np.random.normal(loc=2,scale=1,size=n_class_1),
    'target':[1]*n_class_1
})

df = pd.concat([class_0,class_1]).reset_index(drop=True)

#Check the class Distribution
print(df['target'].value_counts())

target
0    900
1    100
Name: count, dtype: int64

In [36]:
df_minority=df[df['target']==1]
df_majority=df[df['target']==0]

In [45]:
df_majority_downsampled = resample(df_minority,replace=True,
                                   n_samples=len(df_majority),
                                   random_state=42
                                  )

In [46]:
df_majority_downsampled['target'].value_counts()

target
1    900
Name: count, dtype: int64